### ISSUE TITLE
英文回答格式不对

### ISSUE THREAD

**Issue by voyy99** [yihong0618/iWhat#6]
## 问题描述：
- 英文回复的格式不统一，例如`iwhat --en 卧槽`，出现了下面这些情况，有些回复中文，有些格式不对
<img width="912" alt="image" src="https://user-images.githubusercontent.com/45915518/223982038-06039d2a-18e4-430a-9fdf-0042b88deb50.png">

- 有多个Possible answer，也造成的返回格式解析错误
<img width="910" alt="image" src="https://user-images.githubusercontent.com/45915518/223984732-c7119be1-7d21-47a5-8fad-a86f98b0f1bc.png">

## 建议
- 感觉是英文prompt设置的问题，设置成英文问是否更好，另外可以加上一些约束，下面是我随便写了一个prompt，chatgpt的回答：
```
What is '卧槽' might be?
you answer must follow rules below:
1. The answer is json format;
2. The keys are 'What, Maybe, Desc'.
'What' value is the content in the single quote.
'Maybe' value is the most likely thing of the quote content. 
'Desc' value is the description of the quote content.
```
<img width="895" alt="image" src="https://user-images.githubusercontent.com/45915518/223984191-fd258618-e97d-46b4-9224-a4730676fa61.png">

**Comment by yihong0618** [comment]
@Voyageyang 可以。。。。我昨天写完就快速发布了，今天发现了

你有兴趣提个 PR 改一下么

我这么设计你看行么？

--en 走英语的 PROMPT
if self.en:
    self.PROMPT = EN_PROMPT
然后 parse

---
如果没有兴趣，我找时间自己改下，但可能没那么快哈

**Comment by voyageyang** [comment]
好的，我有时间提一下

**Comment by yihong0618** [comment]
@Voyageyang 谢谢
